# Generated by Django 6.0.3 on 2026-03-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='has_delivery',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='has_pickup',
            field=models.BooleanField(default=True),
        ),
    ]
