# Generated by Django 6.0.3 on 2026-03-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_has_delivery_shop_has_pickup'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='delivery_charge',
            field=models.DecimalField(decimal_places=2, default=50.0, max_digits=8),
        ),
    ]
